In [1]:
! ls data

1952-grfp.data	1976-grfp.data	   1997-grfp.data     2009-grfp.data
1953-grfp.data	1977-grfp.data	   1997-hm-grfp.data  2009-hm-grfp.data
1954-grfp.data	1978-grfp.data	   1998-grfp.data     2010-grfp.data
1955-grfp.data	1979-grfp.data	   1998-hm-grfp.data  2010-hm-grfp.data
1956-grfp.data	1980-grfp.data	   1999-grfp.data     2011-grfp.data
1957-grfp.data	1981-grfp.data	   1999-hm-grfp.data  2011-hm-grfp.data
1958-grfp.data	1982-grfp.data	   2000-grfp.data     2012-grfp.data
1959-grfp.data	1983-grfp.data	   2000-hm-grfp.data  2012-hm-grfp.data
1960-grfp.data	1984-grfp.data	   2001-grfp.data     2013-grfp.data
1961-grfp.data	1985-grfp.data	   2001-hm-grfp.data  2013-hm-grfp.data
1962-grfp.data	1986-grfp.data	   2002-grfp.data     2014-grfp.data
1963-grfp.data	1987-grfp.data	   2002-hm-grfp.data  2014-hm-grfp.data
1964-grfp.data	1988-grfp.data	   2003-grfp.data     2015-grfp.data
1965-grfp.data	1989-grfp.data	   2003-hm-grfp.data  2015-hm-grfp.data
1966-grfp.data	1990-grfp.data	   2004-grfp.data     2016-grfp.data
1967-grfp.data	1991-grfp.data	   2004-hm-grfp.data  2016-hm-grfp.data
1968-grfp.data	1992-grfp.data	   2005-grfp.data     2017-grfp.data
1969-grfp.data	1993-grfp.data	   2005-hm-grfp.data  2017-hm-grfp.data
1970-grfp.data	1994-grfp.data	   2006-grfp.data     2018-grfp.data
1971-grfp.data	1994-hm-grfp.data  2006-hm-grfp.data  2018-hm-grfp.data
1972-grfp.data	1995-grfp.data	   2007-grfp.data     2019-grfp.data
1973-grfp.data	1995-hm-grfp.data  2007-hm-grfp.data  2019-hm-grfp.data
1974-grfp.data	1996-grfp.data	   2008-grfp.data     2020-grfp.data
1975-grfp.data	1996-hm-grfp.data  2008-hm-grfp.data  2020-hm-grfp.data

In [2]:
import pandas as pd
import glob

In [3]:
files = sorted(glob.glob('data/*'))

In [4]:
df = pd.DataFrame()

for f in files: # build dataframe including award year
    dfn = pd.read_csv(f, sep='\t', engine='python')
    dfn['Year'] = int(f.split('/')[1].split('-')[0])
    df = pd.concat([df, dfn])

In [5]:
df[df['Current Institution'].str.contains('arlington', na=False, case=False)]

,Name,Baccalaureate Institution,Field of Study,Current Institution,Year
855,"Webb, Michael B",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2006
757,"Hucks, Donald V",University of Texas at Arlington,Life Sciences - other (specify) - Quantitative...,University of Texas at Arlington,2006
917,"Marquez, Claudia P",University of Texas at Arlington,Life Sciences - Genetics,University of Texas at Arlington,2008
1186,"Reyes, Luis R",University of Puerto Rico-Rio Piedras,Chemistry - Organic,University of Texas at Arlington,2008
1000,"Marquez, Claudia Patricia",University of Texas at Arlington,Life Sciences - Genetics,University of Texas at Arlington,2009
1568,"Thompson, Blaine Kealyn",University of Texas at Arlington,Life Sciences - Biochemistry,University of Texas at Arlington,2009
1325,"Nutt, William David",University of Texas at Arlington,Social Sciences - Archaeology,University of Texas at Arlington,2010
1251,"Okolo, Wendy",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2010
774,"Henderson, Laura Suarez",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2011
24,"alsmadi, nesreen M",University of Texas at Arlington,Engineering - Biomedical,University of Texas at Arlington,2011
828,"Hussein, Sarah Moussa",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2014
246,"Card, Daren Carter",SUNY College of Environmental Science and Fore...,Life Sciences - Evolutionary Biology,University of Texas at Arlington,2014
524,"Fuess, Lauren E",College of Charleston,Life Sciences - Ecology,University of Texas at Arlington,2014
85,"Barber, Troy Judson",University of Texas at Arlington,Geosciences - other (specify) - Environmental ...,University of Texas at Arlington,2015
604,"Fuess, Lauren Elizabeth",College of Charleston,Life Sciences - other (specify) - Molecular Ec...,University of Texas at Arlington,2015
721,"Gurak, John Albert",University of Texas at Arlington,Chemistry - Chemical Synthesis,University of Texas at Arlington,2015
897,"Johnson, Kimberly Catherine",Louisiana State University & Agricultural and ...,Social Sciences - Linguistics,The University of Texas at Arlington,2015
651,"Glenn, Priscilla Denise",University of Texas at Arlington,Life Sciences - Genetics,University of Texas at Arlington,2017
1369,"Olawoyin, Omomayowa",University of Texas at Arlington,Mathematical Sciences - Mathematical Biology,University of Texas at Arlington,2017
426,"Currie, Kathleen Louise",University of Texas at Arlington,Life Sciences - Genomics,University of Texas at Arlington,2018
761,"Herzog, Marquerite",National University,Life Sciences - Evolutionary Biology,University of Texas at Arlington,2018
1090,"Maldonado, Jose Alfredo",University of Texas at Arlington,Life Sciences - Evolutionary Biology,University of Texas at Arlington,2019
241,"CLOUD, JOSEPH MICHAEL",University of Texas at Arlington,Comp/IS/Eng - Robotics and Computer Vision,University of Texas at Arlington,2019
318,"CLOUD, JOSEPH MICHAEL",University of Texas at Arlington,Comp/IS/Eng - Robotics and Computer Vision,University of Texas at Arlington,2020
817,"Jaradat, Israa Qasim",Mutah University,Comp/IS/Eng - Computational Science and Engine...,University of Texas at Arlington,2020
1334,"Orr, Melissa",University of Texas at Arlington,Chemistry - Chemical Synthesis,University of Texas at Arlington,2020

In [6]:
df.groupby('Current Institution').size().sort_values(ascending=False)

Current Institution
Stanford University                                                 2080
UNIVERSITY OF CALIFORNIA BERKELEY                                   1649
Massachusetts Institute of Technology                               1645
Harvard University                                                  1542
University of Washington                                            1257
University of California-Berkeley                                   1208
Yale University                                                      992
University of Texas at Austin                                        971
University of Michigan Ann Arbor                                     908
University of Wisconsin-Madison                                      905
Northwestern University                                              890
Columbia University                                                  846
Princeton University                                                 810
Georgia Institute of Technology                                      796
Cornell University                                                   775
California Institute of Technology                                   752
University of Colorado at Boulder                                    734
Duke University                                                      713
University of California-Los Angeles                                 703
University of California-Irvine                                      681
University of California-San Francisco                               670
University of Illinois at Urbana-Champaign                           665
University of Chicago                                                662
University of North Carolina at Chapel Hill                          648
University of California-Davis                                       639
University of Pennsylvania                                           608
CORNELL UNIVERSITY                                                   504
University of California-Santa Barbara                               488
Pennsylvania State Univ University Park                              485
Carnegie-Mellon University                                           480
                                                                    ...
Towson University                                                      1
Tougaloo College                                                       1
The University of the State of New York                                1
The University of Wisconsin                                            1
Institut d'Etudes Politiques de Paris (Sciences Po)                    1
Institute of Criminology, University of Cambridge                      1
International Inst for Indust Env Econ at Lund University              1
The University of Tulsa                                                1
The University of Texas-Rio Grande Valley                              1
JAMES MADISON UNIVERSITY                                               1
The University of Texas at Arlington                                   1
The University of Texas Health Science Center-MD Anderson Cancer       1
Joan and Sanford I. Weill Graduate School of Medical Sciences          1
Johann Wolfgang Goethe University                                      1
Kettering University                                                   1
The University of Tennessee Knoxville                                  1
Johns Hopkins Medical Institute                                        1
The University of Southern Mississippi                                 1
The University of Pennsylvania                                         1
The University of North Carolina - Chapel Hill                         1
The University of New Orleans                                          1
Johns Hopkins University, Whiting School of Engineering                1
Johnson State College                                                  1
The University of Nevada, Reno                                         1
The University of Missouri-System                                      1
The University of Minnesota- Twin Cities                               1
Kean University                                                        1
Kennesaw State University                                              1
The University of Maryland                                             1
the University of Chicago                                              1
Length: 1310, dtype: int64

In [7]:
# Approx num schools who have had ugrads receive GRFP/HM but attend different grad school.
df['Baccalaureate Institution'].unique().shape[0] -  df['Current Institution'].unique().shape[0]

2230