In [1]:
! ls data

1952-grfp.data	1966-grfp.data	1980-grfp.data	1994-grfp.data	2008-grfp.data
1953-grfp.data	1967-grfp.data	1981-grfp.data	1995-grfp.data	2009-grfp.data
1954-grfp.data	1968-grfp.data	1982-grfp.data	1996-grfp.data	2010-grfp.data
1955-grfp.data	1969-grfp.data	1983-grfp.data	1997-grfp.data	2011-grfp.data
1956-grfp.data	1970-grfp.data	1984-grfp.data	1998-grfp.data	2012-grfp.data
1957-grfp.data	1971-grfp.data	1985-grfp.data	1999-grfp.data	2013-grfp.data
1958-grfp.data	1972-grfp.data	1986-grfp.data	2000-grfp.data	2014-grfp.data
1959-grfp.data	1973-grfp.data	1987-grfp.data	2001-grfp.data	2015-grfp.data
1960-grfp.data	1974-grfp.data	1988-grfp.data	2002-grfp.data	2016-grfp.data
1961-grfp.data	1975-grfp.data	1989-grfp.data	2003-grfp.data	2017-grfp.data
1962-grfp.data	1976-grfp.data	1990-grfp.data	2004-grfp.data	2018-grfp.data
1963-grfp.data	1977-grfp.data	1991-grfp.data	2005-grfp.data
1964-grfp.data	1978-grfp.data	1992-grfp.data	2006-grfp.data
1965-grfp.data	1979-grfp.data	1993-grfp.data	2007-grfp.data

In [73]:
import pandas as pd
import glob

In [74]:
files = sorted(glob.glob('data/*'))
print(files[-1])

data/2018-grfp.data

In [75]:
df = pd.DataFrame()

for f in files: # build dataframe including award year
    dfn = pd.read_csv(f, sep='\t', engine='python')
    dfn['Year'] = int(f.split('/')[1].split('-')[0])
    df = pd.concat([df, dfn])

In [80]:
df[df['Baccalaureate Institution'].str.contains('arlington', na=False, case=False)]

,Name,Baccalaureate Institution,Field of Study,Current Institution,Year
8,"Anderson, Grant B",U of Texas-Arlington,NaN,NaN,1968
300,"Levy, David L",U of Texas-Arlington,Engineering - Industrial,NaN,1972
196,"Gonzalez, Roberto Jr",U of Texas-Arlington,Life Sciences - Entomology,NaN,1981
203,"Green, Jeffrey S",U of Texas-Arlington,Social Sciences - Political Science,NaN,1981
153,"Freeman, Donald Gary",U of Texas-Arlington,Social Sciences - Economics (Business Administ...,NaN,1982
154,"Gaines, Stanley O",U of Texas-Arlington,Psychology - Social,NaN,1986
801,"Towb, Parmalee C",U of Texas-Arlington,Life Sciences - Biophysics,NaN,1993
876,"Throckmorton, Chandra Stacey","TEXAS,U-ARLINGTON",E - ELECTRCL,NaN,1997
557,"Meintser, Sherri Lynn",U of Texas-Arlington,E - ENVIRON,NaN,1998
626,"Rives, Julia E.",U of Texas-Arlington,NEUROSCI -,NaN,2000
278,"Galindo, Cristi Lara",U of Texas-Arlington,BIOLOGY -,NaN,2001
161,"Dallas, Natalya",U of Texas-Arlington,E - ELECTRCL,NaN,2003
855,"Webb, Michael B",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2006
963,"Koen, Joshua David",University of Texas at Arlington,Psychology - Cognitive Neuroscience,University of California-Davis,2010
1325,"Nutt, William David",University of Texas at Arlington,Social Sciences - Archaeology,University of Texas at Arlington,2010
774,"Henderson, Laura Suarez",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2011
1177,"McCarthy, Emily Ruth",University of Texas at Arlington,Engineering - Civil Engineering,William Marsh Rice University,2011
1838,"Torres, Raul",University of Texas at Arlington,Life Sciences - Genomics,University of California-San Francisco,2013
608,"Garcia-Barboza, Beatriz Jael",University of Texas at Arlington,Chemistry - Chemistry of Life Processes,University of Southern California,2014
828,"Hussein, Sarah Moussa",University of Texas at Arlington,Engineering - Aeronautical and Aerospace,University of Texas at Arlington,2014
1449,"Poteet, Steven Andrew",University of Texas at Arlington,Chemistry - Chemical Catalysis,University of California-Irvine,2014
85,"Barber, Troy Judson",University of Texas at Arlington,Geosciences - other (specify) - Environmental ...,University of Texas at Arlington,2015
721,"Gurak, John Albert",University of Texas at Arlington,Chemistry - Chemical Synthesis,University of Texas at Arlington,2015
1432,"Phillips, Lori Brooke",University of Texas at Arlington,Social Sciences - Archaeology,Washington State University,2015
276,"Castillo, Erica Araceli",University of Texas at Arlington,Engineering - Mechanical,Stanford University,2016
693,"Gutierrez, Stephanie Olga",University of Texas at Arlington,STEM Education and Learning Research - Science...,Purdue University,2016
651,"Glenn, Priscilla Denise",University of Texas at Arlington,Life Sciences - Genetics,University of Texas at Arlington,2017
1369,"Olawoyin, Omomayowa",University of Texas at Arlington,Mathematical Sciences - Mathematical Biology,University of Texas at Arlington,2017
1935,"Watson, Sara",University of Texas at Arlington,Social Sciences - Archaeology,University of California-Davis,2017
435,"Currie, Kathleen Louise",University of Texas at Arlington,Life Sciences - Genomics,University of Texas at Arlington,2018